"use strict";
exports.__esModule = true;
var express_1 = require("express");
var notesSchema_1 = require("../schemas/notesSchema");
var validateSchema_1 = require("../middlewares/validateSchema");
var notesController_1 = require("../controllers/notesController");
var notesRouter = (0, express_1.Router)();
notesRouter.post('/notes', (0, validateSchema_1.validateSchemaMiddleware)(notesSchema_1.noteSchema), notesController_1.createNotes);
notesRouter.get('/notes', notesController_1.getNote);
notesRouter.get('/notes/:id', notesController_1.getNotes);
notesRouter["delete"]('/notes/:id', notesController_1.deleteNotes);
exports["default"] = notesRouter;
